[2024-05-21T16:37:51.872+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T16:37:51.880+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T16:35:42.721674+00:00 [queued]>
[2024-05-21T16:37:51.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T16:35:42.721674+00:00 [queued]>
[2024-05-21T16:37:51.884+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-05-21T16:37:51.890+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-21 16:35:42.721674+00:00
[2024-05-21T16:37:51.894+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=9762) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-21T16:37:51.895+0000] {standard_task_runner.py:63} INFO - Started process 9764 to run task
[2024-05-21T16:37:51.895+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-21T16:35:42.721674+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmp5ykh24kq']
[2024-05-21T16:37:51.896+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask transform_load_weather_data
[2024-05-21T16:37:51.917+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-21T16:35:42.721674+00:00 [running]> on host 39024998a807
[2024-05-21T16:37:51.956+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T16:35:42.721674+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T16:35:42.721674+00:00'
[2024-05-21T16:37:51.957+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T16:37:53.103+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-21T16:37:53.104+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T16:37:53.120+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-21T16:35:42.721674+00:00, execution_date=20240521T163542, start_date=20240521T163751, end_date=20240521T163753
[2024-05-21T16:37:53.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-21T16:37:53.172+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T16:37:53.174+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
